name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: flutter test
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: flutter/sib_utrecht_app
