name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      - run: flutter --version
        shell: bash
      - run: flutter pub get
        shell: bash
        working-directory: flutter/sib_utrecht_app

        # Based on code from https://github.com/bluefireteam/flutter-gh-pages
        #- uses: bluefireteam/flutter-gh-pages@v8
        #  with:
        #    workingDir: flutter/sib_utrecht_app

      - run: flutter config --enable-web
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: flutter build web --release --web-renderer=canvaskit --base-href /
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: touch build/web/.nojekyll
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: echo "sib-utrecht.vincentk.nl" > build/web/CNAME
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: git config user.name github-actions
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: git config user.email github-actions@github.com
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: git --work-tree build/web add --all
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: git commit -m "Automatic deployment by github-actions"
        shell: bash
        working-directory: flutter/sib_utrecht_app
      - run: git push origin HEAD:gh-pages --force
        shell: bash
        working-directory: flutter/sib_utrecht_app
